package completion

import (
	"testing"

	"github.com/open-southeners/tusk-php/internal/models"
	"github.com/open-southeners/tusk-php/internal/parser"
	"github.com/open-southeners/tusk-php/internal/protocol"
	"github.com/open-southeners/tusk-php/internal/symbols"
)

// TestVariableGenericPropagation verifies that generic type parameters survive
// through variable assignments, so that:
//
//	$categories = Category::query()->get();  // Collection<int, Category>
//	$firstCategory = $categories->first();   // ?Category
func TestVariableGenericPropagation(t *testing.T) {
	p := setupRealisticEloquentTest(t)

	resolveTyped := func(expr, source string, line int) string {
		file := parser.ParseFile(source)
		rt := p.ResolveExpressionTypeTyped(expr, source, protocol.Position{Line: line}, file)
		return rt.String()
	}

	source := `<?php
use App\Models\Category;

$categories = Category::query()->get();

$firstCategory = $categories->first();

$name = $firstCategory->name;
`

	t.Run("$categories is Collection<int, Category>", func(t *testing.T) {
		typ := resolveTyped("$categories", source, 5)
		if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
			t.Errorf("expected Collection<int, Category>, got %q", typ)
		}
	})

	t.Run("$categories->first() returns ?Category", func(t *testing.T) {
		typ := resolveTyped("$categories->first()", source, 5)
		if typ != "?App\\Models\\Category" {
			t.Errorf("expected ?Category, got %q", typ)
		}
	})

	t.Run("$firstCategory is ?Category", func(t *testing.T) {
		typ := resolveTyped("$firstCategory", source, 7)
		if typ != "?App\\Models\\Category" {
			t.Errorf("expected ?Category, got %q", typ)
		}
	})
}

// TestVariableGenericCompletions verifies that completions work through
// variable assignments with generic types.
func TestVariableGenericCompletions(t *testing.T) {
	p := setupRealisticEloquentTest(t)

	t.Run("$categories-> shows Collection methods", func(t *testing.T) {
		source := `<?php
use App\Models\Category;
$categories = Category::query()->get();
$categories->`
		// len("$categories->") = 13
		items := p.GetCompletions("file:///test.php", source, protocol.Position{Line: 3, Character: 13})
		labels := collectLabels(items)

		for _, m := range []string{"first", "count", "all", "map"} {
			if !labels[m] {
				t.Errorf("expected Collection method %q after $categories->, got: %v", m, labels)
			}
		}
	})

	t.Run("$firstCategory-> shows Category model members", func(t *testing.T) {
		source := `<?php
use App\Models\Category;
$categories = Category::query()->get();
$firstCategory = $categories->first();
$firstCategory->`
		items := p.GetCompletions("file:///test.php", source, protocol.Position{Line: 4, Character: 16})
		labels := collectLabels(items)

		if !labels["save"] {
			t.Errorf("expected 'save' from Model on $firstCategory->, got: %v", labels)
		}
		if !labels["name"] {
			t.Errorf("expected 'name' property on $firstCategory->, got: %v", labels)
		}
	})
}

// TestDocblockMethodQueryResolution verifies that @method docblock-generated
// query() with union return type "Builder<static>|Category" resolves correctly
// through late static binding, matching real IDE helper output.
func TestDocblockMethodQueryResolution(t *testing.T) {
	idx := symbols.NewIndex()
	idx.RegisterBuiltins()

	// Real vendor Model with query() returning Builder<static>
	idx.IndexFile("file:///vendor/Model.php", `<?php
namespace Illuminate\Database\Eloquent;
abstract class Model {
    /** @return \Illuminate\Database\Eloquent\Builder<static> */
    public static function query() {}
    public function save(): bool {}
    public function toArray(): array {}
}
`)
	idx.IndexFile("file:///vendor/Builder.php", `<?php
namespace Illuminate\Database\Eloquent;
class Builder {
    /** @return $this */
    public function where($column, $operator = null, $value = null) {}
    /** @return \Illuminate\Database\Eloquent\Model|null */
    public function first() {}
    /** @return \Illuminate\Database\Eloquent\Collection */
    public function get($columns = []) {}
    /** @return $this */
    public function with($relations) {}
}
`)
	idx.IndexFile("file:///vendor/Collection.php", `<?php
namespace Illuminate\Database\Eloquent;
class Collection extends \Illuminate\Support\Collection {}
`)
	idx.IndexFile("file:///vendor/SupportCollection.php", `<?php
namespace Illuminate\Support;
class Collection {
    /** @return mixed */
    public function first($callback = null, $default = null) {}
    /** @return array */
    public function all() {}
    /** @return int */
    public function count() {}
}
`)

	// Category with @method docblock (as generated by IDE helper)
	// This is the REAL scenario: @method static Builder<static>|Category query()
	idx.IndexFile("file:///app/Category.php", `<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\Category query()
 */
class Category extends Model {
    public string $name;
}
`)

	models.AnalyzeEloquentModels(idx, "/tmp")
	p := NewProvider(idx, nil, "laravel")

	resolveTyped := func(expr, source string, line int) string {
		file := parser.ParseFile(source)
		rt := p.ResolveExpressionTypeTyped(expr, source, protocol.Position{Line: line}, file)
		return rt.String()
	}

	source := `<?php
use App\Models\Category;

$c = Category::all();
$fc = $c->first();

$categories = Category::query()->get()->all();

$firstCategory = $categories[0];
`

	t.Run("Category::query() returns Builder<Category> via @method with static resolution", func(t *testing.T) {
		typ := resolveTyped("Category::query()", source, 4)
		if typ != "Illuminate\\Database\\Eloquent\\Builder<App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("Category::query()->get() returns Collection<int, Category>", func(t *testing.T) {
		typ := resolveTyped("Category::query()->get()", source, 4)
		if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("Category::query()->get()->all() returns array", func(t *testing.T) {
		typ := resolveTyped("Category::query()->get()->all()", source, 4)
		if typ != "array" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("$c = Category::all() is Collection<int, Category>", func(t *testing.T) {
		typ := resolveTyped("$c", source, 4)
		if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("$fc = $c->first() is ?Category", func(t *testing.T) {
		typ := resolveTyped("$fc", source, 5)
		if typ != "?App\\Models\\Category" {
			t.Errorf("got %q", typ)
		}
	})
}

// TestRealVendorTemplateResolution uses Builder with @template TModel and
// @return Collection<int, TModel> — exactly matching real Laravel vendor files.
func TestRealVendorTemplateResolution(t *testing.T) {
	idx := symbols.NewIndex()
	idx.RegisterBuiltins()

	// Real vendor Model with query() returning Builder<static>
	idx.IndexFile("file:///vendor/Model.php", `<?php
namespace Illuminate\Database\Eloquent;
/**
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\Illuminate\Database\Eloquent\Model query()
 */
abstract class Model {
    public function save(): bool {}
    public function toArray(): array {}
}
`)
	// Real vendor Builder with @template TModel and @return Collection<int, TModel>
	idx.IndexFile("file:///vendor/Builder.php", `<?php
namespace Illuminate\Database\Eloquent;
/**
 * @template TModel of \Illuminate\Database\Eloquent\Model
 */
class Builder {
    /** @return $this */
    public function where($column, $operator = null, $value = null) {}
    /** @return TModel|null */
    public function first() {}
    /** @return \Illuminate\Database\Eloquent\Collection<int, TModel> */
    public function get($columns = []) {}
    /** @return $this */
    public function with($relations) {}
    /** @return $this */
    public function orderBy($column, $direction = 'asc') {}
}
`)
	idx.IndexFile("file:///vendor/Collection.php", `<?php
namespace Illuminate\Database\Eloquent;
/**
 * @template TKey of array-key
 * @template TModel of \Illuminate\Database\Eloquent\Model
 */
class Collection extends \Illuminate\Support\Collection {
    /** @return TModel|null */
    public function find($key, $default = null) {}
}
`)
	idx.IndexFile("file:///vendor/SupportCollection.php", `<?php
namespace Illuminate\Support;
/**
 * @template TKey of array-key
 * @template TValue
 */
class Collection {
    /** @return TValue|null */
    public function first($callback = null, $default = null) {}
    /** @return array<TKey, TValue> */
    public function all() {}
    /** @return int */
    public function count() {}
}
`)

	idx.IndexFile("file:///app/Category.php", `<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Category extends Model {
    public string $name;
}
`)

	models.AnalyzeEloquentModels(idx, "/tmp")
	p := NewProvider(idx, nil, "laravel")

	resolveTyped := func(expr, source string, line int) string {
		file := parser.ParseFile(source)
		rt := p.ResolveExpressionTypeTyped(expr, source, protocol.Position{Line: line}, file)
		return rt.String()
	}

	source := `<?php
use App\Models\Category;


`

	t.Run("Category::query() → Builder<Category>", func(t *testing.T) {
		typ := resolveTyped("Category::query()", source, 3)
		if typ != "Illuminate\\Database\\Eloquent\\Builder<App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("Category::query()->get() → Collection<int, Category> via @template TModel", func(t *testing.T) {
		typ := resolveTyped("Category::query()->get()", source, 3)
		if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("Category::query()->get()->first() → ?Category via @template TModel chain", func(t *testing.T) {
		typ := resolveTyped("Category::query()->get()->first()", source, 3)
		if typ != "?App\\Models\\Category" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("Category::query()->get()->all() → array", func(t *testing.T) {
		typ := resolveTyped("Category::query()->get()->all()", source, 3)
		// all() returns array<TKey, TValue> — with generics this should have params
		// but for now array is acceptable
		if typ != "array<int, App\\Models\\Category>" && typ != "array" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("Category::query()->where()->orderBy()->get() → Collection<int, Category>", func(t *testing.T) {
		typ := resolveTyped("Category::query()->where('x', 1)->orderBy('y')->get()", source, 3)
		if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("Category::query()->first() → ?Category via @template TModel", func(t *testing.T) {
		typ := resolveTyped("Category::query()->first()", source, 3)
		if typ != "?App\\Models\\Category" {
			t.Errorf("got %q", typ)
		}
	})

	t.Run("variable: $categories = Category::query()->get()", func(t *testing.T) {
		varSource := `<?php
use App\Models\Category;
$categories = Category::query()->get();
$fc = $categories->first();
`
		typ := resolveTyped("$categories", varSource, 3)
		if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
			t.Errorf("$categories: got %q", typ)
		}

		typ2 := resolveTyped("$fc", varSource, 4)
		if typ2 != "?App\\Models\\Category" {
			t.Errorf("$fc: got %q", typ2)
		}
	})
}

// TestEloquentMagicMethodGenerics verifies that all Eloquent virtual static
// methods (magic methods forwarded from __callStatic) correctly propagate
// the model type through Builder and Collection generics.
func TestEloquentMagicMethodGenerics(t *testing.T) {
	p := setupRealisticEloquentTest(t)

	resolveTyped := func(expr, source string) string {
		file := parser.ParseFile(source)
		rt := p.ResolveExpressionTypeTyped(expr, source, protocol.Position{Line: 5}, file)
		return rt.String()
	}

	preamble := "<?php\nuse App\\Models\\Category;\n\n\n\n"

	// Methods returning Builder<Category>
	builderMethods := []string{
		"Category::query()",
		"Category::where('name', 'test')",
		"Category::whereIn('id', [1, 2])",
		"Category::whereNull('name')",
		"Category::orderBy('name')",
		"Category::latest()",
		"Category::with('products')",
		"Category::select('id', 'name')",
		"Category::limit(10)",
	}
	for _, expr := range builderMethods {
		t.Run(expr+" returns Builder<Category>", func(t *testing.T) {
			typ := resolveTyped(expr, preamble)
			if typ != "Illuminate\\Database\\Eloquent\\Builder<App\\Models\\Category>" {
				t.Errorf("got %q", typ)
			}
		})
	}

	// Methods returning Collection<int, Category>
	collectionMethods := []string{
		"Category::get()",
		"Category::all()",
	}
	for _, expr := range collectionMethods {
		t.Run(expr+" returns Collection<int, Category>", func(t *testing.T) {
			typ := resolveTyped(expr, preamble)
			if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
				t.Errorf("got %q", typ)
			}
		})
	}

	// Methods returning the model itself
	modelMethods := []string{
		"Category::first()",
		"Category::find(1)",
		"Category::firstOrFail()",
		"Category::findOrFail(1)",
		"Category::create(['name' => 'test'])",
	}
	for _, expr := range modelMethods {
		t.Run(expr+" returns Category", func(t *testing.T) {
			typ := resolveTyped(expr, preamble)
			if typ != "App\\Models\\Category" {
				t.Errorf("got %q", typ)
			}
		})
	}

	// Chained Builder methods still return Builder<Category>
	t.Run("chained builders preserve generic", func(t *testing.T) {
		typ := resolveTyped("Category::where('a', 1)->orderBy('b')->with('c')", preamble)
		if typ != "Illuminate\\Database\\Eloquent\\Builder<App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	// Builder->first() returns ?Category (through generic)
	t.Run("Builder<Category>::first() returns ?Category", func(t *testing.T) {
		typ := resolveTyped("Category::where('a', 1)->first()", preamble)
		if typ != "?App\\Models\\Category" {
			t.Errorf("got %q", typ)
		}
	})

	// Builder->get() returns Collection<int, Category>
	t.Run("Builder<Category>::get() returns Collection<int, Category>", func(t *testing.T) {
		typ := resolveTyped("Category::where('a', 1)->get()", preamble)
		if typ != "Illuminate\\Database\\Eloquent\\Collection<int, App\\Models\\Category>" {
			t.Errorf("got %q", typ)
		}
	})

	// Collection->first() returns ?Category
	t.Run("Collection<int, Category>::first() returns ?Category", func(t *testing.T) {
		typ := resolveTyped("Category::get()->first()", preamble)
		if typ != "?App\\Models\\Category" {
			t.Errorf("got %q", typ)
		}
	})
}
