#!/usr/bin/env bash
# fetch-corpus.sh — clone corpus repos listed in testdata/corpus/manifest.json
#
# Usage:
#   bash scripts/fetch-corpus.sh [--tier pr|nightly|all]
#
# Default tier: all
#
# Each repo is shallow-cloned at the pinned ref into testdata/corpus/_repos/<name>/.
# After cloning, the resolved commit SHA is recorded in testdata/corpus/corpus.lock.
# corpus.lock is the TRUE pin and should be committed to the repository after the
# first successful run so that subsequent CI runs are byte-for-byte reproducible.
#
# The script is idempotent: a repo directory that already exists at the correct SHA
# is skipped without re-cloning.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MANIFEST="${REPO_ROOT}/testdata/corpus/manifest.json"
REPOS_DIR="${REPO_ROOT}/testdata/corpus/_repos"
LOCK_FILE="${REPO_ROOT}/testdata/corpus/corpus.lock"

TIER="all"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --tier)
      if [[ -z "${2:-}" ]]; then
        echo "ERROR: --tier requires an argument (pr|nightly|all)" >&2
        exit 1
      fi
      TIER="$2"
      shift 2
      ;;
    --tier=*)
      TIER="${1#--tier=}"
      shift
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      echo "Usage: $0 [--tier pr|nightly|all]" >&2
      exit 1
      ;;
  esac
done

case "${TIER}" in
  pr|nightly|all) ;;
  *)
    echo "ERROR: --tier must be one of: pr, nightly, all (got: '${TIER}')" >&2
    exit 1
    ;;
esac

# ---------------------------------------------------------------------------
# Dependency check — require jq for JSON parsing
# ---------------------------------------------------------------------------
if ! command -v jq &>/dev/null; then
  echo "ERROR: 'jq' is required but not installed." >&2
  echo "  Install with: brew install jq  (macOS) or  apt-get install jq  (Debian/Ubuntu)" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log() { echo "[fetch-corpus] $*"; }

mkdir -p "${REPOS_DIR}"

# Start fresh lock accumulation for this run (append-mode so parallel use
# is possible, but we rewrite at the end of a clean run).
declare -a LOCK_LINES=()

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
TOTAL=$(jq '[.[] | select(type == "object" and has("name"))] | length' "${MANIFEST}")
FETCHED=0
SKIPPED=0

log "Manifest: ${MANIFEST}"
log "Target tier: ${TIER}"
log "Repos directory: ${REPOS_DIR}"
echo ""

while IFS= read -r entry; do
  name=$(echo "${entry}"  | jq -r '.name')
  repo=$(echo "${entry}"  | jq -r '.repo')
  ref=$(echo "${entry}"   | jq -r '.ref')
  tier=$(echo "${entry}"  | jq -r '.tier')

  # Filter by requested tier
  if [[ "${TIER}" != "all" && "${tier}" != "${TIER}" ]]; then
    continue
  fi

  dest="${REPOS_DIR}/${name}"

  log "Processing ${name} (tier=${tier}, ref=${ref})"

  # Check if already cloned and at the right ref/SHA
  if [[ -d "${dest}/.git" ]]; then
    current_sha=$(git -C "${dest}" rev-parse HEAD 2>/dev/null || true)
    # Attempt to resolve the ref to a SHA from the existing clone's refs
    wanted_sha=$(git -C "${dest}" rev-parse "refs/tags/${ref}" 2>/dev/null \
                  || git -C "${dest}" rev-parse "refs/heads/${ref}" 2>/dev/null \
                  || git -C "${dest}" rev-parse "${ref}" 2>/dev/null \
                  || true)
    if [[ -n "${current_sha}" && -n "${wanted_sha}" && "${current_sha}" == "${wanted_sha}" ]]; then
      log "  -> already at ${current_sha:0:12} — skipping"
      LOCK_LINES+=("${name} ${current_sha}")
      SKIPPED=$((SKIPPED + 1))
      continue
    fi
    log "  -> stale clone (have ${current_sha:0:12}, want ${ref}) — re-cloning"
    rm -rf "${dest}"
  fi

  # Shallow clone at the requested ref
  mkdir -p "$(dirname "${dest}")"
  log "  -> cloning ${repo} at ${ref}"
  git clone --quiet --depth 1 --branch "${ref}" "${repo}" "${dest}"

  resolved_sha=$(git -C "${dest}" rev-parse HEAD)
  log "  -> resolved SHA: ${resolved_sha}"
  LOCK_LINES+=("${name} ${resolved_sha}")
  FETCHED=$((FETCHED + 1))

done < <(jq -c '.[] | select(type == "object" and has("name"))' "${MANIFEST}")

# ---------------------------------------------------------------------------
# Write lock file
# ---------------------------------------------------------------------------
{
  echo "# corpus.lock — generated by scripts/fetch-corpus.sh"
  echo "# This file is the TRUE pin for corpus repos. Commit it after the first"
  echo "# successful run so CI always checks out identical source."
  echo "# Format: <name> <commit-sha>"
  for line in "${LOCK_LINES[@]}"; do
    echo "${line}"
  done
} > "${LOCK_FILE}"

echo ""
log "Done. Fetched=${FETCHED} Skipped=${SKIPPED} Total entries processed=$((FETCHED + SKIPPED))"
log "Lock file written to: ${LOCK_FILE}"
